site:
  domain: example.com
  type: blog

wordpress:
  replicaCount: 1

  image:
    repository: wordpress-wpbuilder
    tag: "1.0"
    pullPolicy: IfNotPresent

  admin:
    email: admin@example.com

  # Plugins that should be installed
  plugins: []

  # Theme that should be installed
  theme: ""

  persistence:
    enabled: true
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 10Gi

mariadb:
  enabled: true

  image:
    repository: mariadb
    tag: "11.4"
    pullPolicy: IfNotPresent

  database: wordpress
  username: wordpress
  password: wordpress-password
  rootPassword: root-password

  persistence:
    enabled: true
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 5Gi

ingress:
  enabled: true
  className: nginx