site:
  domain: example.com
  type: blog

wordpress:
  replicaCount: 1

  image:
    repository: wordpress
    tag: latest
    pullPolicy: IfNotPresent

  admin:
    email: admin@example.com

  theme: ""
  plugins: []

  persistence:
    enabled: true
    size: 10Gi

mariadb:
  enabled: true

  image:
    repository: mariadb
    tag: "11.4"
    pullPolicy: IfNotPresent

  database: wordpress
  username: wordpress
  password: wordpress-password
  rootPassword: root-password

  persistence:
    enabled: true
    size: 5Gi

ingress:
  enabled: true
  className: nginx