apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-mariadb

  labels:
    app: {{ .Release.Name }}-mariadb

spec:
  replicas: 1

  selector:
    matchLabels:
      app: {{ .Release.Name }}-mariadb

  template:

    metadata:
      labels:
        app: {{ .Release.Name }}-mariadb

    spec:

      containers:

        - name: mariadb

          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"

          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}

          ports:
            - name: mysql
              containerPort: 3306

          env:

            - name: MARIADB_ROOT_PASSWORD
              value: {{ .Values.mariadb.rootPassword | quote }}

            - name: MARIADB_DATABASE
              value: {{ .Values.mariadb.database | quote }}

            - name: MARIADB_USER
              value: {{ .Values.mariadb.username | quote }}

            - name: MARIADB_PASSWORD
              value: {{ .Values.mariadb.password | quote }}

          volumeMounts:

            - name: mariadb-data
              mountPath: /var/lib/mysql

      volumes:

        - name: mariadb-data

          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mariadb