apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ .Release.Name }}-mariadb

  labels:
    app: {{ .Release.Name }}-mariadb

spec:

  accessModes:
    - {{ .Values.mariadb.persistence.accessMode }}

  storageClassName: {{ .Values.mariadb.persistence.storageClass }}

  resources:

    requests:
      storage: {{ .Values.mariadb.persistence.size }}