apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app: {{ .Release.Name }}-wordpress
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wordpress
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wordpress
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
          imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
          ports:
            - containerPort: 80